development:
  secret_key_base: e6ebe05f458e14651c9bbb3afdc2ef6ad6d7a0ee64244136f9317d5b49cc0871
test:
  secret_key_base: fba803cea34bbccd3956f6a8438ba9dc3dd3c68c9845ae6b3754c6ae9540f708
production:
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'thereisnoproductionsecret,thatisprettydangerous.ButForlocalTestsW€admitThatsOK:)') %>

